export {Support} from './Support'
export {HelpCenter} from './HelpCenter'
export {FeedBack} from './FeedBack'
export {Report} from './Report'
export {Suggestion} from './Suggestion'
export {FAQ} from './FAQ'